imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        server_version: 5.6

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_rest:
    routing_loader:
        default_format: json
        include_format: true
    param_fetcher_listener: force
    body_listener: true
    allowed_methods_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
           - { path: '^/api/', priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
           - { path: '^/', stop: true }
    versioning: true

jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-d\\TH:i:s" # ATOM
            default_timezone: "WET" # defaults to whatever timezone set in php.ini or via date_default_ti
    visitors:
        json:
            options: JSON_PRETTY_PRINT

nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['GET']
                max_age: 3600

nelmio_api_doc: ~


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
            address: info@fresh.lu
            sender_name: heichwaasser.lu

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles:        [ AppBundle ]
    filters:
        cssrewrite: ~
        lessphp:
           file: "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"

easy_admin:
    site_name: "Héichwaasser"
    entities:
        River:
            class: AppBundle\Entity\River
        Station:
            class: AppBundle\Entity\Station
            label: 'Station'
            list:
                      fields:
                           - city
                           - river
                           - supplement
                           - latitude
                           - longitude
                           - measurements
                           - minimum
                           - maximum
                           - current
                      sort: ['city', 'ASC']
            edit:
                     fields:
                           - city
                           - river
                           - shortname
                           - supplement
                           - latitude
                           - longitude
            new:
                      fields:
                           - city
                           - river
                           - shortname
                           - supplement
                           - latitude
                           - longitude
                           - measurements
        Measurement:
            class: AppBundle\Entity\Measurement
        AlertLevel:
            class: AppBundle\Entity\AlertLevel