security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ~
        ROLE_ADMIN:       ~

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            http_basic:
                realm: 'Secured Demo Area'
                provider: fos_userbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin/*, role: ROLE_ADMIN }
